# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6261b3108307dca8531dab40a0a86399b8cb48b69a28607cf451f86efa3c15f26a98ff3fb95bbd52166aef9195185f32f9a42d2b61eaeeec727263ca014f6c37

test:
  secret_key_base: 66bc2fa9565b5391e9971bd09ee3d76a7a2ea0d693b39d42a691faee18e3d39ab62d202a8adf5167f30786bf4c72f6ed5959c283e007428358bea641baf08052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
